# Generated by Django 3.1.4 on 2021-01-07 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romaji', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Kana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=2)),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kana.sound')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kana.type')),
            ],
        ),
    ]
