# Generated by Django 3.1.4 on 2021-01-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('romaji_sound', models.CharField(max_length=50)),
                ('kana_sound', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Radical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=2)),
                ('stroke_count', models.IntegerField()),
                ('meaning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kanji.meaning')),
                ('reading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kanji.sound')),
            ],
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=2)),
                ('stroke_count', models.IntegerField()),
                ('meanings', models.ManyToManyField(to='kanji.Meaning')),
                ('readings', models.ManyToManyField(to='kanji.Sound')),
                ('tags', models.ManyToManyField(to='kanji.Tag')),
            ],
        ),
    ]
